function alphab = get_alpha_band(eeg, Fs)
%ALPHA Returns a discrete-time filter object.
%
% Generated on: 23-Oct-2009 14:31:40
% M-File generated by MATLAB(R) 7.5 and the Signal Processing Toolbox 6.8.
% Equiripple Bandpass filter designed using the FIRPM function.
% All frequency values are in Hz.
Fs = Fs;  % Sampling Frequency
Fstop1 = 7.5;             % First Stopband Frequency
Fpass1 = 8;               % First Passband Frequency
Fpass2 = 12;              % Second Passband Frequency
Fstop2 = 12.5;            % Second Stopband Frequency
Dstop1 = 0.0001;          % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor
% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);
% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);
alphab = filter(Hd,eeg);
end
